name: dart2closure
author: "Chirayu Krishnappa <chirayu@chirayuk.com>"
homepage: https://github.com/dart-lang/web-ui
description: An easy way to build web apps in Dart.
version: 0.0.1
dependencies:
  args: any
  analyzer_experimental:
    git: /Users/chirayu/work/analyzer_experimental
    # git: git@github.com:chirayuk/dart_ast
  logging: ">=0.3.5+1"
  pathos: ">=0.4.1"
  source_maps: ">=0.4.1 <0.4.2"
  unittest: ">=0.3.5+1"
dev_dependencies:
  js: any
  benchmark_harness: ">=1.0.2 <1.0.3"
environment:
  sdk: ">=0.4.3"
