name: analyzer_experimental
version: 0.1.5
author: Dart Team <misc@dartlang.org>
description: Experimental static analyzer for Dart.
homepage: http://www.dartlang.org
dependencies:
  args: any
  browser: 0.4.2
  unittest: any
